const flagCodesByTeamId: Record<string, string> = {
  mex: "mx",
  can: "ca",
  rsa: "za",
  jpn: "jp",
  usa: "us",
  ger: "de",
  gha: "gh",
  qat: "qa",
  bra: "br",
  mar: "ma",
  sco: "gb-sct",
  egy: "eg",
  arg: "ar",
  den: "dk",
  nga: "ng",
  nzl: "nz",
  esp: "es",
  uru: "uy",
  kor: "kr",
  nor: "no",
  fra: "fr",
  sen: "sn",
  par: "py",
  aus: "au",
  eng: "gb-eng",
  ned: "nl",
  irn: "ir",
  jam: "jm",
  ita: "it",
  chi: "cl",
  tun: "tn",
  ksa: "sa",
  bel: "be",
  ecu: "ec",
  cro: "hr",
  pan: "pa",
  sui: "ch",
  alg: "dz",
  pol: "pl",
  crc: "cr",
  por: "pt",
  cod: "cd",
  uzb: "uz",
  col: "co",
  aut: "at",
  srb: "rs",
  tur: "tr",
  per: "pe",
  cze: "cz",
  bih: "ba",
  hai: "ht",
  cuw: "cw",
  civ: "ci",
  swe: "se",
  cpv: "cv",
  irq: "iq",
  jor: "jo",
};

export const getFlagUrl = (teamId: string) => {
  const code = flagCodesByTeamId[teamId];
  return code ? `https://flagcdn.com/${code}.svg` : null;
};
